position_joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    arm_id: panda

cartesian_velocity_controller:
    type: panda_ros_controllers/CartesianVelocityController
    arm_id: panda

cartesian_pose_impedance_controller:
    type: panda_ros_controllers/CartesianPoseImpedanceController
    arm_id: panda
